### ISSUE TITLE
Iframe's height should be 500px

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-html-runner#10]
### Before
<img width="1440" alt="screen shot 2017-10-24 at 14 53 26" src="https://user-images.githubusercontent.com/4105740/31959504-400d6df0-b8cb-11e7-8154-50b69237a2b0.png">

### After
<img width="1440" alt="screen shot 2017-10-24 at 14 53 53" src="https://user-images.githubusercontent.com/4105740/31959505-403031fa-b8cb-11e7-8586-e9816c9de5be.png">

**Comment by fedescarpa** [comment]
If page height is grater than 500px, is scrollbar shown?

**Comment by fedescarpa** [comment]
@aguspina, If page height is grater than 500px, is scrollbar shown?

**Comment by aguspina** [comment]
yup

**Comment by flbulgarelli** [comment]
And why not just adapting the height of the page to the page content? 

The 500px limit is completely arbitrary

**Comment by fedescarpa** [comment]
fixed in https://github.com/mumuki/mumuki-styles/commit/4a1cc22438b4090616317386964aa35e739196c1#diff-316fd3fdc6ef8d450c3d15ea0339dd5dR64

The browser maintenance 16:9 aspect ratio
