### ISSUE TITLE
Trim text inside HTML tags...

### ISSUE THREAD

**Issue by fedescarpa** [mumuki/mumuki-html-runner#34]
If you compare the following HTMLs are different when should be equals

```html
<ul>
  <li> Programación con objetos </li>
  <li> Ruby </li>
  <li> HTML </li>
</ul>
```

```html
<ul>
  <li>Programación con objetos</li>
  <li>Ruby</li>
  <li>HTML</li>
</ul>
```

**Comment by Javi** [comment]
Should they really be equal? While working on this I considered the following case: 
``` 
    <body>This is<span> a test </span>case</body>
``` 
versus
``` 
    <body>This is <span>a test</span>case</body>
``` 

There are cases where whitespaces make a difference in content. Should we just ignore any ' ' character at all when comparing answers? Are there exercises where we test something other than tags? Should I go ahead and just trim every node's leading and trailing whitespaces?

**Comment by flbulgarelli** [comment]
I think yes, we should ignore trailing whitespaces, eventhough they are not strictly the same, but in very similar.

However, I think it would be nice if we could optionally provide an options.yml file in the HTML tests, with a flag for enabling or disabling strict checking - disabled by default.
