### ISSUE TITLE
Agregar aserciones para el manejo del DOM

### ISSUE THREAD

**Issue by fedescarpa** [mumuki/mumuki-html-runner#35]
- [x] Algunos ejercicios serán exclusivamente de sintaxis de JS y entiendo que basta con el motor actual de Mumuki
- [x] Otros ejercicios serán integrando HTML + CSS + JS. Algunos ejemplos de ejercicios y validaciones:
  - [x] Asegurar que el archivo HTML integre de forma correcta el archivo JS
  - [x] Asegurar que usen determinadas funciones que permitan hacer manejo de dom. (Por ejemplo querySelector) y verificar que hayan obtenido los elementos del DOM correctos
  - [x] Verificar uso de funciones abocadas al browser (console.log, alert, prompt, confirm, etc)
  - [x] Verificar el uso de funciones que modifican el dom (por ejemplo, innerHTML aunque también valen funciones que modifiquen clases o atributos). Se puede verificar desde el uso de la función o desde la verificación de el DOM resultante
  - [x] Verificacion de definición de eventos. Por ejemplo que haya un "onclick" en un elemento del DOM. Habría que validar 
    - [x] Que el elemento del DOM sea correcto
    - [x] Que el evento sea el correcto
    - [x] Que la función callback haga lo esperado
  - [x]  Que haya soporte a pedidos por AJAX. No hay un requerimiento puntual acerca de si hacerlo con xhttprequest, jquery u otras librerias

**Comment by rodri042** [comment]
Dejo las cosas que se me ocurrieron hasta ahora:

(Ahora mismo el que integra y genera el DOM final es el Precompile Hook del runner (lado del servidor)...)

---

## Opción 1: Todo del lado del servidor

Permitir un formato 2.0 de `test`, usando sections. Ejemplo:
```
/*<output#*/
<html>
	<body>
		...
		<!-- mismo formato de test anterior -->
	</body>
</html>
/*#output>*/

/*<tests#*/
describe("cosas del dom", function() {
	it("modifica el título de la página", function() {
		oldDocument.title.should.be.eql("título viejo");
		document.title.should.be.eql("título nuevo");
	});
});
/*#tests>*/
```
(tanto 'output' como 'tests' son opcionales, como antes)

Esto se ejecutaría en un worker con node dentro del Test Hook usando [node-jsdom](https://github.com/gobstones/gobstones-cli/blob/de19de4d3ad8fada5eba6919ff05d55581b1c841/src/blockly/blocklyCompiler.js#L7) y en el Expectations Hook se podrían chequear expectativas del código de JS con mulang (que soporta nativamente JS así que no problem con eso).

- Para validar que le pegue o no a alguna URL con AJAX podría usarse algo como [nock](https://github.com/nock/nock).
- Supongo que se podrá chequear que ciertos eventos como "onclick" hayan sido creados en un elemento, [aunque stackoverflow diga que no se pueda](https://stackoverflow.com/questions/9046741/get-event-listeners-attached-to-node-using-addeventlistener/10030771#10030771).

---

## Opción 2: Todo del lado del cliente

La lógica de sections está hecha en Ruby y no sé si vale la pena pasarla a client side, el test podría ser algo más simple como un JSON: (o YAML)
```json
{
  "expected_html": "<html>...</html>",
  "tests": "describe('...')..."
}
```

- Hay que pasar [la lógica que mergea los assets](https://github.com/mumuki/mumuki-html-runner/blob/730882f571ffd3906d56764c6c018a521805f293/lib/precompile_hook.rb#L8) al lado del cliente.
- Un "js custom" del runner de html podría leer el `test`, validar si es del formato nuevo, y si es así engancharse del evento "voy a correr la solución" y hacer todo del lado del cliente:
	- Comparar el DOM
	- Correr los tests con mocha client side
	- Correr mulang client side
	- Retornar algo similar a lo que retorna `new mumuki.bridge.Laboratory().runTests(...)` para que muestre los tests correctos/fallidos y el resultado final.
- Por más que se haga todo en el cliente hay que pegarle al servidor (no necesariamente al runner) para que recuerde la última solución enviada.

---

En ambos casos hay que:
- Actualizar bibliotheca para que genere los tests en el formato correcto.
- Hacer que se puedan mostrar resultados de tests, expectativas, y el mini browser todo junto (no estoy seguro si ahora eso se puede)

**Comment by fedescarpa** [comment]
Hoy en día esta en beta lo de mulang en client side, @flbulgarelli ?

La opción 2 creo que me convence más pero no tengo una opinión super formada. @rodri042 vos por cuál irías y por que?

**Comment by rodri042** [comment]
@fedescarpa también me parece más eficiente la segunda, pero también sé que tomaría bastante más trabajo y tiene algunos agregados de incertidumbre:
- La responsabilidad de comparar el DOM y alguna cosa más quedará duplicada entre cliente y servidor y habría que ver qué hacer con eso
- Correr los tests con mocha client side, OK, pero ¿se puede? tendría que correr los scripts sobre el DOM del ejercicio y no sobre el actual, que sería el de Laboratory. No estoy seguro de cómo lograr eso
- Correr mulang client side no sé qué tan complicado es

La primera opción en cambio la veo más posible en el corto plazo

**Comment by fedescarpa** [comment]
Bueno, vayamos por la primera opción entonces
