### ISSUE TITLE
No funcionan los múltiples archivos

### ISSUE THREAD

**Issue by rgonzalezt** [mumuki/mumuki-html-runner#46]
Si se hace un ejercicio con múltiples archivos y se sube un .html y un .css, por más que se linkee el css al html no aparece nada en el navegador donde se muestran los resultados. Si se elimina el archivo .css, quedando solo el .html, recién ahí se muestra algo en el navegador de prueba (como un ejercicio normal de html).

**Comment by julian-berbel** [comment]
No lo estaría pudiendo reproducir
![Peek 2019-04-26 09-26](https://user-images.githubusercontent.com/11720274/56807511-79da8500-6805-11e9-8277-502f7b0230d9.gif)

Tenés algún ejercicio + solución con lo que lo pueda probar @rgonzalezt ?

**Comment by rgonzalezt** [comment]
https://mumuki.io/primaria.staging/exercises/7517-representacion-de-la-informacion-multiples-archivos 

Yo lo estoy probando ahí.

**Comment by julian-berbel** [comment]
por lo que veo lo que sucede es que está hardcodeado en el código del multifile_hook que el archivo principal tiene que tener el nombre index.html. La idea sería modificar esto para que pueda tener cualquier nombre @flbulgarelli ?

**Comment by flbulgarelli** [comment]
No es necesario, pero si al menos que se valide apropiadamente está situación y que se documente.
